#!/usr/bin/env python3

height = 7
all_chars = list(map(chr, range(0x20, 0x60)))

data = {}
min_index = 0x20
max_index = 0x60
with open("font-master.txt", "r") as f:
    for c in all_chars:
        data[c] = {}
        data[c]["description"] = f.readline().strip()[1:]
        data[c]["rawbits"] = []
        for row in range(height):
            rawbits = f.readline().strip()
            data[c]["rawbits"].append(rawbits)

print("; Wizard Replay Mono pixel font")
print("; (c) 2025 by 4am")
print("; license:Open Font License 1.1, see OFL.txt")
print("; derived from Replay Mono, (c) 2025 by 4am")
print("; https://github.com/a2-4am/fonts/tree/main/Wizard%20Replay%20Mono")
print(";")
print("; - includes only uppercase letters and basic punctuation")
print(";   (ASCII $20-$5F) and replaces @ with a cursor shape")
print("; - has a vertical spacing line above each character")
print(";   instead of below, to match Wizardry's original font behavior")
print(";")
print("; This file is automatically generated")
print(";")
print()
print(f"kFontDataMin = {hex(ord(all_chars[0]))} ; ASCII value of first character")
for row in range(height):
    print(f"FontDataRow{row}")
    for c in map(chr, range(min_index, max_index)):
        description = data[c]['description']
        bits = "1" + data[c]["rawbits"][row][::-1]
        print(f"         !byte %{bits} ; {description}")
print("FontDataRow7")
for c in map(chr, range(min_index, max_index)):
    description = data[c]['description']
    bits = "10000000"
    print(f"         !byte %{bits} ; {description}")
